using StockApplicationASPNetWebMVCIndividualIdentity.Application.IncomeStatements;

namespace StockApplicationASPNetWebMVCIndividualIdentity.Application.Repository;

public interface IIncomeStatementRepository : IRepository<IncomeStatementDto>
{
}